version: '2.1'

services:

  ############################
  # Local Machine Containers #
  ############################

  web:
    build: .
    command: ./start.sh
    volumes:
      - ./:/app
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PASSWORD: password
      DB_USER: root
    depends_on:
      db:
        condition: service_healthy  
    
    
  db:
    image: mysql:5.7
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: "stock_tracker"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 6  
      
volumes:
  mysql-data:
    driver: local    