version: '2.1'

services:

  ############################
  # Local Machine Containers #
  ############################

  web:
    build: .
    command: ./start.sh
    volumes:
      - ./:/app
    ports:
      - "8080:80"
    