swagger: "2.0"
info:
  description: swagger file for stocks tracking application
  version: "1.0.0"
  title: Stocks Tracking Application
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api/v1"

# Paths supported by the server application
paths:
  /stocks:
    get:
      operationId: "stocks.get"
      tags:
        - "Stocks"
      summary: "The stock data structure supported by the server application"
      description: "Read a list of stock ticker symbols"
      responses:
        200:
          description: "Successful read stock symbols"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "string"
                ticker_symbol:
                  type: "string"
                timestamp:
                  type: "string"